services:
  db:
    image: postgres:17
    container_name: sa_app_db
    restart: always
    environment:
      - POSTGRES_DB=SA_AppDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      # Montaje directo a carpeta local para persistencia absoluta
      - ./.docker/db_data:/var/lib/postgresql/data

  app:
    image: saas_asaas_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sa_app_web
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=SA_AppDB;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    volumes:
      # Volumen persistente para archivos de usuario (Uploads)
      - ./.docker/user_uploads:/app/wwwroot/uploads
    depends_on:
      - db
